.TH "include Directory Reference" 3 "Version v1.0.0" "SmartBMS_2209A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBq76pl455\&.h\fP"
.br
.RI "Header file for interfacing with the BQ76PL455A-Q1 battery management IC\&. "
.ti -1c
.RI "file \fBCan\&.h\fP"
.br
.RI "CAN communication interface for ESP32\&. "
.ti -1c
.RI "file \fBd2cc_lib\&.h\fP"
.br
.RI "Header file for the D2CC library\&. "
.ti -1c
.RI "file \fBLedTaskInit\&.h\fP"
.br
.RI "LED initialization and control tasks for ESP32\&. "
.ti -1c
.RI "file \fBTcpServer\&.h\fP"
.br
.RI "TCP server implementation for ESP32\&. "
.ti -1c
.RI "file \fBUart\&.h\fP"
.br
.RI "UART driver interface for ESP32\&. "
.ti -1c
.RI "file \fBWifi\&.h\fP"
.br
.RI "Wi-Fi configuration for ESP32 in AP+STA mode\&. "
.in -1c
