.TH "src/Can.c" 3 "Version v1.0.0" "SmartBMS_2209A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Can.c \- CAN driver implementation for the ESP32 using the TWAI driver\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Can\&.h'\fP
.br
\fR#include 'd2cc_lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBCan_Init\fP (twai_general_config_t can_gpio_config, twai_timing_config_t can_time_config, twai_filter_config_t can_filter_config)"
.br
.RI "Initializes the CAN (TWAI) driver with the specified configurations\&. "
.ti -1c
.RI "uint8_t \fBCan_Transmit\fP (twai_message_t message, uint8_t data[])"
.br
.RI "Transmits a CAN message with the specified data\&. "
.ti -1c
.RI "void \fBCanReporter\fP (void *pvParameter)"
.br
.RI "Task function to periodically report CAN messages\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDbcStruct\fP \fBmaindbc_struct\fP"
.br
.RI "Structure to hold CAN message data\&. "
.ti -1c
.RI "twai_message_t \fBCan_Main\fP = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBCan_Main_ID\fP, \&.data_length_code = 8, \&.data = {0},}"
.br
.ti -1c
.RI "twai_message_t \fBBattery_Messages\fP = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBBattery_Messages_ID\fP, \&.data_length_code = 8, \&.data = {0},}"
.br
.ti -1c
.RI "twai_message_t \fBBattery_Voltages\fP = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBCan_Battery_Voltages_ID\fP, \&.data_length_code = 8, \&.data = {0},}"
.br
.ti -1c
.RI "twai_message_t \fBBattery_Temperatures\fP = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBCan_Battery_Temperatures_ID\fP, \&.data_length_code = 8, \&.data = {0},}"
.br
.ti -1c
.RI "uint8_t \fBData_Of_Can_Main\fP [8] = {0, 1, 2, 3, 4, 5, 6, 7}"
.br
.ti -1c
.RI "uint8_t \fBData_Of_Battery_Messages\fP [8] = {8, 9, 10, 11, 12, 13, 14, 15}"
.br
.ti -1c
.RI "uint8_t \fBData_Of_Battery_Voltages\fP [8] = {16, 17, 22, 32, 42, 52, 62, 72}"
.br
.ti -1c
.RI "uint8_t \fBData_Of_Battery_Temperatures\fP [8] = {35, 13, 23, 33, 43, 53, 63, 73}"
.br
.in -1c
.SH "Detailed Description"
.PP 
CAN driver implementation for the ESP32 using the TWAI driver\&. 


.PP
\fBDate\fP
.RS 4
18 December 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
hakimmc 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "uint8_t Can_Init (twai_general_config_t can_gpio_config, twai_timing_config_t can_time_config, twai_filter_config_t can_filter_config)"

.PP
Initializes the CAN (TWAI) driver with the specified configurations\&. Initializes the CAN interface\&.

.PP
\fBParameters\fP
.RS 4
\fIcan_gpio_config\fP General configuration for the CAN GPIO pins and mode\&. 
.br
\fIcan_time_config\fP Timing configuration for the CAN bus (e\&.g\&., bitrate)\&. 
.br
\fIcan_filter_config\fP Filter configuration for message acceptance\&. 
.RE
.PP
\fBReturns\fP
.RS 4
uint8_t Returns 1 if the driver is successfully initialized\&. 
.RE
.PP

.SS "uint8_t Can_Transmit (twai_message_t message, uint8_t data[])"

.PP
Transmits a CAN message with the specified data\&. Transmits a CAN message\&.

.PP
\fBParameters\fP
.RS 4
\fImessage\fP The CAN message structure to transmit\&. 
.br
\fIdata\fP The data array to be sent with the message\&. 
.RE
.PP
\fBReturns\fP
.RS 4
uint8_t Returns 1 if the transmission is successful\&. 
.RE
.PP

.SS "void CanReporter (void * pvParameter)"

.PP
Task function to periodically report CAN messages\&. Task to report CAN messages\&.

.PP
This function initializes the CAN driver and repeatedly transmits preconfigured CAN messages, using data from the \fR\fBDbcStruct\fP\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIpvParameter\fP A pointer to any parameters passed to the task (unused)\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "twai_message_t Battery_Messages = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBBattery_Messages_ID\fP, \&.data_length_code = 8, \&.data = {0},}"

.SS "twai_message_t Battery_Temperatures = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBCan_Battery_Temperatures_ID\fP, \&.data_length_code = 8, \&.data = {0},}"

.SS "twai_message_t Battery_Voltages = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBCan_Battery_Voltages_ID\fP, \&.data_length_code = 8, \&.data = {0},}"

.SS "twai_message_t Can_Main = {\&.extd = 0, \&.rtr = 0, \&.ss = 0, \&.self = 0, \&.dlc_non_comp = 0, \&.identifier = \fBCan_Main_ID\fP, \&.data_length_code = 8, \&.data = {0},}"

.SS "uint8_t Data_Of_Battery_Messages[8] = {8, 9, 10, 11, 12, 13, 14, 15}"

.SS "uint8_t Data_Of_Battery_Temperatures[8] = {35, 13, 23, 33, 43, 53, 63, 73}"

.SS "uint8_t Data_Of_Battery_Voltages[8] = {16, 17, 22, 32, 42, 52, 62, 72}"

.SS "uint8_t Data_Of_Can_Main[8] = {0, 1, 2, 3, 4, 5, 6, 7}"

.SS "\fBDbcStruct\fP maindbc_struct\fR [extern]\fP"

.PP
Structure to hold CAN message data\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SmartBMS_2209A from the source code\&.
