.TH "Phys_Value_t" 3 "Version v1.0.0" "SmartBMS_2209A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Phys_Value_t \- factor, offset and value variable structer for CAN messages structure for message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d2cc_lib\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfactor\fP"
.br
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
factor, offset and value variable structer for CAN messages structure for message\&. 

This structure including factor, offset and value variables\&. 
.SH "Member Data Documentation"
.PP 
.SS "float Phys_Value_t::factor"

.SS "int Phys_Value_t::offset"

.SS "float Phys_Value_t::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for SmartBMS_2209A from the source code\&.
